<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistCourseraConfiguration' => 'configuration/ArcanistCourseraConfiguration.php',
    'ArcanistCourseraLintWorkflow' => 'workflow/ArcanistCourseraLintWorkflow.php',
    'ArcanistESLintLinter' => 'linters/ArcanistESLintLinter.php',
    'ArcanistJSXHintLinter' => 'linters/ArcanistJSXHintLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistCourseraConfiguration' => 'ArcanistConfiguration',
    'ArcanistCourseraLintWorkflow' => 'ArcanistWorkflow',
    'ArcanistESLintLinter' => 'ArcanistExternalLinter',
    'ArcanistJSXHintLinter' => 'ArcanistExternalLinter',
  ),
));
